[tools]
python = "3.11.9"
ruby = "3.2.5"

[env]
_.python.venv = ".venv"
EXPANDED_CODE_SIGN_IDENTITY=""
EXPANDED_CODE_SIGN_IDENTITY_NAME=""
EXPANDED_PROVISIONING_PROFILE=""
DEFAULT_XCODEPROJ="Punycode.xcodeproj"
DEFAULT_PODSPEC="Punycode.podspec"
SCHEME_IOS="Punycode-iOS"
SCHEME_MACOS="Punycode-macOS"
SCHEME_TVOS="Punycode-tvOS"
SCHEME_IOS_TEST="Punycode-iOSTests"
SCHEME_MACOS_TEST="Punycode-macOSTests"
SCHEME_TVOS_TEST="Punycode-tvOSTests"